# Generated by Django 5.0.1 on 2024-01-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiclass', '0002_director_genre_film_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='year',
            field=models.DateField(),
        ),
    ]
